version: '3'

services:
  weather_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:4200
    environment:
      - XRapidAPIKeyHeaderValue=${XRapidAPIKeyHeaderValue}
    command: ng serve --host 0.0.0.0
