version: '3'

services:
  weather_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    environment:
      - API_KEY=${API_KEY}
    command: ng serve --host 0.0.0.0
